 # Full attack in use
    
    This is the test file for this Python module

In [1]:
#!pip install pyomo
#!pip install hsnf==0.3.13

In [2]:
import attackfuleeca
from datetime import datetime
import pandas as pd

Solver you already have
['base', 'gurobi', 'highs']


In [3]:
attack = attackfuleeca.attack()

In [4]:
print(attack)

Hello, I am the python class used to attack FuLeeca,
 I can be used to generate a key pair for FuLeeca,
 I also can load a public key from a file,
 I format the public key so that it can be used in Pyomo,
, I use Pyomo to attack the FuLeeca cryptosystem and you got to choose which solver to use!


In [5]:
attack.generate_key(verbose =True)

p is5
halfn is 11
Alice's a value: [ 1 -2  0 -2 -1  1  0 -2  1  0  1]
Alice's b value: [-1  0  2  1  0 -1  0 -1  2  1  2]
Alice's T value: 
[[2 0 1 1 3 3 2 1 0 0 2]
 [2 2 0 1 1 3 3 2 1 0 0]
 [0 2 2 0 1 1 3 3 2 1 0]
 [0 0 2 2 0 1 1 3 3 2 1]
 [1 0 0 2 2 0 1 1 3 3 2]
 [2 1 0 0 2 2 0 1 1 3 3]
 [3 2 1 0 0 2 2 0 1 1 3]
 [3 3 2 1 0 0 2 2 0 1 1]
 [1 3 3 2 1 0 0 2 2 0 1]
 [1 1 3 3 2 1 0 0 2 2 0]
 [0 1 1 3 3 2 1 0 0 2 2]]
This should be 1 if the sekret keys are valid
1


In [6]:
T = attack.get_T('T.csv')

In [7]:
print(attack.T_to_dat(T, level = 0))

Task done, see your file at toyexample.dat
param level:=0; 
param p:= 5; 
param uba:= 2; 
param halfn:= 11; 
param: i:
       Mset:=
      1 0
      2 0
      3 0
      4 1
      5 1
      6 2
      7 2
      8 2
      9 1
      10 1
      11 1; 
param T:  1 2 3 4 5 6 7 8 9 10 11:=
        1 2 0 1 1 3 3 2 1 0 0 2
        2 2 2 0 1 1 3 3 2 1 0 0
        3 0 2 2 0 1 1 3 3 2 1 0
        4 0 0 2 2 0 1 1 3 3 2 1
        5 1 0 0 2 2 0 1 1 3 3 2
        6 2 1 0 0 2 2 0 1 1 3 3
        7 3 2 1 0 0 2 2 0 1 1 3
        8 3 3 2 1 0 0 2 2 0 1 1
        9 1 3 3 2 1 0 0 2 2 0 1
        10 1 1 3 3 2 1 0 0 2 2 0
        11 0 1 1 3 3 2 1 0 0 2 2; 
param Q1:  1 2 3 4 5 6 7 8 9 10 11:=
        1 0 0 0 0 0 0 0 0 0 0 0
        2 3 1 0 3 4 0 1 1 1 1 0
        3 2 3 0 2 1 3 0 1 1 1 0
        4 2 1 2 2 0 0 3 0 1 1 0
        5 2 1 1 4 0 4 0 3 0 1 0
        6 3 3 0 3 2 4 4 0 3 0 0
        7 3 3 2 4 2 2 0 0 1 4 0
        8 3 0 0 1 4 3 4 2 2 3 0
        9 1 1 1 4 2 1 1 2 0 0 0
        10 3 1 2 0 3 2 2 2 3 1 0
   

In [8]:
attack.forge_lin_sk(solvername = 'gurobi', ampl = False,verbose = True)

[    0.00] starting timer
We just have built the instance, start solving stay tuned!
Solver script file: '/local_scratch/pbs.1413564.pbs02/tmpnos152d5.gurobi.script'
Solver log file: 'my.log'
Solver solution file: '/local_scratch/pbs.1413564.pbs02/tmpe78vsqkh.gurobi.txt'
Solver problem files: ('/local_scratch/pbs.1413564.pbs02/tmpcabfof0u.pyomo.lp',)
feasible
0
Verifying that indeed aT = b mod p 
 This should be 1 if the sekret keys are valid:

1
[+  30.83] task 1
elapsed time: 30.8 s
Value of a[1, 1, 0, 2, 0, 1, 2, 1, 1, 2, 0]
Value of b[3, 0, 3, 0, 1, 1, 3, 4, 1, 4, 0]
Value of aT[3 0 3 0 1 1 3 4 1 4 0]


[1, 30.829138132743537]

In [9]:
#LEVEL 1
names = ["level1ex"+str(i) for i in range(10)]

In [10]:
names

['level1ex0',
 'level1ex1',
 'level1ex2',
 'level1ex3',
 'level1ex4',
 'level1ex5',
 'level1ex6',
 'level1ex7',
 'level1ex8',
 'level1ex9']

In [11]:
def generate_instance(name):
    level = 1
    pkfilename = 'generatedpk/' + name +'T.csv'
    dat_name = 'dat_files/' + name
    skfilename = "originalsk/" + name + "level1sk.txt"
    forgedskname = "forgedsk/" + name + "level1sk.txt"
    infolist = [level, pkfilename, skfilename,forgedskname]
    #generate the key 
    attack.generate_key(level = level, pkfilename = pkfilename, skfilename = skfilename)
    T = attack.get_T(pkfilename)
    #format the key
    attack.T_to_dat(T, level=level, filename = dat_name)

In [12]:
for name in names: #do not run this anymore 
    generate_instance(name)

p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex0.dat
p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex1.dat
p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex2.dat
p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex3.dat
p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex4.dat
p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex5.dat
p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex6.dat
p is65521
halfn is 659
This should be 1 if the sekret keys are valid
1
Task done, see your file at dat_files/level1ex7.dat
p is65521
halfn 

# Just testing if the FuLeeca Submission really does what I think is doing


In [5]:
import numpy as np

In [16]:
# The length should be 659 

In [17]:
len([38,1,24,65515,60,65511,65510,40,65484,5,0,24,19,54,65420,65434,65492,114,0,65428,1,65510,32,65506,44,65508,65480,16,0,28,0,0,654665479,56,0,57,65495,55,65509,65466,6,31,75,0,3,65513,18,65509,14,23,65397,35,65460,65501,48,65414,65438,16,65513,7,154,65491,20,1,35,65519,65475,65512,65514,67,10,11,0,16,65492,6,65434,0,65444,65468,65501,8,99,98,17,65381,65482,22,65374,65506,65483,65496,1046,124,65511,4,65508,65520,65515,65520,65474,53,85,142,40,65496,65505,38,65493,0,38,148,65382,65485,72,56,129,19,2,65519,65482,9,665515,127,21,122,65497,65498,65378,19,65488,65487,6,31,65401,65518,125,65425,65466,66,65366,65450,65520,24,3,102,7,16,117,65514,619,65365,25,2,70,0,13,52,0,148,65484,65500,65512,0,17,44,4,65485,26,12,14,18,0,65412,65363,0,65444,65520,32,48,65503,65369,65453,32,44,65478,120,143,65509,110,65414,62,32,85,65442,65504,65517,0,18,8,65376,65514,65380,117,65432,113,65476,65501,65418,12,65484,6,65387,65445,39,65386,65497,65458,65495,65450,146,65376,65510,33,65438,8,154,65428,86,118,5,65382,65415,65364,65473,65409,65500,7,65504,65377,14,65425,0,65475,65494,65487,0,65490,65398,20,51,25,7,0,7,29,65413,156,65488,65503,65440,8,65493,5,39,22,65519,653884,108,65510,65517,66,65504,36,65370,65464,65508,65439,21,7,0,65468,65497,27,0,65496,3,29,65518,72,31,65424,58,0,3,27,30,23,655195476,0,0,0,30,0,65499,65499,126,155,2,14,2,40,65433,35,0,105,65407,19,65385,65493,65511,65471,45,1,0,65495,65488,36,17,15,22,43,6,39,140,13,12,65411,19,65383,24,16,3,0,0,25,135,65519,0,15,34,49,5,65516,65465,30,65512,0,50,15,130,98,33,5,65513,65383,47,65418,0,37,12,0,5,0,23,12,63,65510,65463,5,65512,65506,149,65433,65518,0,94,65437,126,65482,43,65472,65511,29,65393,15,94,21,65406,131,668,65515,65495,65368,65490,82,7,65426,65513,74,0,65470,80,26,65483,54,65429,7,111,91,65514,0,65508,130,2,65435,65394,1,15,65375,1,22,65448,41,56,65474,68,12,65518,65518,69,65415,65512,65494,10,65503,97,1,102,65393,109,4,0,80,65498,65363,65459,0,0,65503,654945513,32,0,113,65371,41,65488,29,65389,65467,9,65508,0,25,32,59,65511,15,65500,118,65517,50,30,65402,20,65510,4,65370,65400,2,654965516,51,31,65364,14,65511,65389,0,46,11,65467,65405,84,65464,150,65476,7,46,34,90,70,65520,9,0,65456,3,133,21,65505,92,9,36,6536,125,81,0,28,65517,65430,65502,65422,121,51,13,65507,101,65509,78,65388,57,65504,65385,69,0,0,34,65368,49,5,65502,65511,25,15,37,5402,65516,65442,65498,11,65515,67,65463,100,65517,65466,65469,100,14,34,65486,65486,65499,65399,142,65456,65495,65502,14,14,42,678,65446,65485,0,65501,6,95,22,65380,28,0,65504,37,20,65503,65486,65461,38,116,65469,13,65518,65416,65372,65497,111,47,65479,6552
])

609

In [18]:
len([21,65504,65511,65447,0,65507,28,147,65473,65518,65507,65488,32,51,65510,137,65368,65450,65511,50,0,65380,132,45,0,65504,78,65494,0,65517,53,0,34,11,65511,6,65515,65517,0,52,41,0,44,65391,65418,65519,32,118,65497,155,65389,65501,123,4,65446,65511,26,15,4,7,33,0,65466,65404,65491,65479,65514,5,1,58,46,0,2,65412,48,65473,65464,94,65447,32,65484,65517,2,1,65479,140,65504,65475,65500,65503,31,46,35,120,65416,65448,0,65429,2,25,37,152,65368,36,69,149,126,12,5,65494,6,43,0,27,79,26,65513,102,65458,34,18,65433,138,65456,474,50,2,65444,65363,0,65422,65513,65485,24,141,52,76,0,96,1,56,0,121,65423,0,127,24,65512,148,65485,81,5,0,19,38,157,21,26,45,0,452,1,91,65439,150,71,19,0,65499,65465,90,65495,113,43,86,65370,3,122,65514,29,65506,65504,14,0,28,38,41,11,65440,8,65514,65516,613,65509,40,136,0,139,38,51,65517,64,39,65515,65502,65512,156,65434,152,7,17,15,80,0,65393,65451,65449,65515,0,65501,0,65477,0,657,65492,118,3,65379,1,0,35,65375,110,65370,13,13,40,65372,65504,65484,0,2,53,65398,65471,65415,10,45,65507,0,0,65492,33,58,38,127514,27,65407,35,49,135,65499,65519,65513,0,112,65379,134,65453,65376,1,100,65492,29,1,65508,65510,51,4,65502,65496,65489,61,23,655,55,65454,65508,134,0,150,65482,15,14,65434,144,0,75,22,65375,44,65417,65505,65486,0,85,65410,65514,26,65486,86,65382,65509,73,89,54,65518,65495,0,65512,23,65386,65451,28,137,65509,10,65430,148,0,14,0,12,0,23,83,65449,18,25,16,57,65507,65494,130,2,26,65499,25,65485,65507,65406,15,47,65508,84,2,39,8,65411,20,65509,15,65422,65472,79,61,23,138,0,16,11,65377,65493,59,31,30,65518,65505,6565399,11,65495,65509,18,24,7,36,65498,65475,89,18,65405,65473,107,0,65424,65483,65518,65502,65501,94,5,0,65518,39,4,20,120,65518,0,11,9,65505,88,47,31,80,65496,65466,0,65505,65499,65498,65487,65429,65488,65500,65405,27,65469,25,65416,65517,78,33,65367,0,654874,20,65490,65518,29,65490,65364,2,97,65520,6,65512,65490,65419,7,65420,65431,62,65392,65516,51,100,41,65512,19,98,0,43,65514,64,1519,0,65476,66,65483,0,33,65506,65501,0,65497,42,49,65415,65388,57,82,65432,25,62,23,83,5,65516,65512,65510,131,104,65507,39,12,697,65479,6,65406,19,65496,65486,40,65509,0,44,0,65513,49,65493,65388,65513,65490,65517,53,4,13,111,21,6,65508,16,65513,0,65463,6519,65515,65468,0,129,65512,65456,65518,10,65513,9,76,96,65500,65484,65467,65393,65501,0,65418,65516,30,58,4,0,9,156,5,143,15,67,161,0,65467,0,65464,65499,65519,17,37,65489,65390,5,65400,65520,65404,47,109,65504,30,65437,65414,65367,0,23,65397,65493,65407,1588,19,126,65436,65514,65515,65505,65497,59,43,93,65428,40,11,65508,65510,22,65376,34,65467,65491,65396,136,65413,12,10,18,68
])

613

In [19]:
len([229,5385,8149,30278,41253,58010,45945,53544,5266,40030,15943,9303,50541,9876,16483,58072,3491,1266,2312,27760,2468,62193,42552,34340,62084,30914,21747,62801,1281,58376,10095,56907,33681,35504,8904,38416,29829,6731,16093,21471,48242,52658,40375,22258,19676,182633,63431,53568,65055,48352,10439,4752,34314,62756,37133,57836,18362,58541,2642,12558,21345,49815,64565,47952,33538,39596,44974,0,13279,40366,24744,8038,20492,48794,5187,43438,36787,37144,45916,29918,690,16905,33061,54057,56965,23607,39015,43166,26712,15448,32507,25765,3210,32283,23147,30661,2403,51883,42364,53726,32107,43566,34723,24670,14052,50125,38729,35562,21429,40471,25351,449041,13053,53103,17209,38853,56820,715,16838,30376,7578,13397,28174,20999,1418,9116,10006,2356,40225,32787,10424,55245,55559,38287,223990,9456,36370,43208,53998,64640,63055,4467,37093,5119,2951,25813,251,11712,23301,23922,58070,43125,49601,1842,5525,38336,4764,47219,50193,46308,8130,58159,31293,32466,24317,39578,42566,61674,16766,37077,17945,44448,4493,27273,3133,39479,16286,33322,35014,0,45460,379,181,14253,21091,27926,54476,11676,16530,13649,57151,58304,56637,26064,24580,11242,27495,43775,61580,56796,60842,21907,0,36323,11745,40032,5942,7725,741,41989,39185,58622,42273,57797,6189,64035,3630,27796,21847,55690,44241,37038,56238,14581,15064,365982,15820,13688,5223,7122,21998,42661,13714,39074,36814,32186,25280,46442,18727,39830,25377,8363,43795,51942,52359,20628,2322,239328,48101,38916,35297,41289,51932,63258,44299,36076,37301,55160,39474,46254,60844,36726,14140,45100,63252,56004,41945,37106,34660,14327,52870,5775,47925,59951,15556,64221,36934,37608,24418,15091,2116,27881,43431,42805,29151,32463,9053,46595,37527,10670,60037,62091,45468,4596,2051,43986,51258,2037,65434,20938,10382,8595,29572,33010,7278,6658,28353,53472,41071,6412,38020,1535,26173,230766,37954,29609,57839,6602,52685,33024,14127,5873,63399,65511,7653,14948,10321,6603,26806,28524,25390,46232,58840,27366,38911,461426,61855,44344,48793,47337,2397,30468,18169,28155,51421,58529,16946,11022,1449,33232,48553,53228,40211,46104,38844,36363,58871,510360,5694,42015,51948,7245,17319,1836,34373,25838,31493,59920,26029,6032,58879,29958,59895,19838,34447,9778,22285,45774,35818,64581,13487,35212,24344,57023,48933,19613,20596,24930,5291,28155,55899,26289,37348,20103,21374,22269,62592,54367,6745,25347,558,478286,20772,57679,59975,36948,51885,49792,26566,52953,40557,37515,28015,38495,10492,52237,32934,54624,48526,7053,64319,15032,33221,54668,4232,33330,38617,64583,65416,19886,22574,19124,31110,64620,28687,1713,12334,15648,51070,35511,27865,52823,19878,65354,4697,0,51928,16363,61646,31572,35111,34263,28349,2813,15984,20247,33294,4402,10858,64468,34633,26400,62664,60984,57216,37202,24077,240650,46505,14491,43629,60432,57480,48255,12783,60905,26642,35035,54138,8693,63092,49825,61697,30356,24610,28041,28321,62755,54291,245181,4627,43743,12346,45,3440,58479,41434,20316,14337,13717,33713,53481,53218,60720,64181,25450,27818,37134,29248,16475,5680,214076,37250,17057,30217,15136,14871,27849,47760,27815,13784,50863,55179,36084,21091,50018,8986,47073,16327,29984,2009,28422,4885,422063,28466,43799,58747,47606,2814,23760,60708,39936,28830,36998,33283,53292,31016,12607,799,35012,59623,32358,10176,65176,13720,654396,38636,13325,24967,36443,54535,2545,22872,33281,44022,51324,3210,43555,63183,29478,63758,28162,50768,1739,54481,41891,51531,0,61541,44492,6602,43818,62667,33093,9897,56222,12685,40201,13838,7825,32732,28692,59660,36104,59858,2006,38585,6210,4485,27202,24494,24284,60327,48792,63275,65248,40698,25886,38687,65384
])

610